import { ReactNode } from 'react';

import { Rule } from '@sanity/types';

export interface DokumentBase {
  title: string;
  type: SanityTyper.DOCUMENT;
  fields: Field[];
  name: DokumentNavn;
}

export interface SpørsmålDokumentBase {
  type: SanityTyper.DOCUMENT;
  fields: Field[];
}

export interface StegDokument extends DokumentBase {
  steg: Steg;
}

export type Field = FieldBase &
  (
    | {
        type: SanityTyper.OBJECT;
        description?: string;
        validation?: (rule: Rule) => Rule;
      }
    | { description: `${string | undefined}${'(obligatorisk)'}`; validation: (rule: Rule) => Rule }
    | { description: `${string | undefined}${'(frivillig)'}`; validation?: (rule: Rule) => Rule }
  );

interface FieldBase {
  name: string;
  title: string | ReactNode;
  [key: string]: unknown;
}

export enum SanityTyper {
  STRING = 'string',
  REFERENCE = 'reference',
  BOOLEAN = 'boolean',
  OBJECT = 'object',
  ARRAY = 'array',
  BLOCK = 'block',
  DOCUMENT = 'document',
  TABLE = 'table',
}

export enum CustomSanityTyper {
  CUSTOM_BLOCK = 'customBlock',
  LOCALE_STRING = 'localeString',
  LOCALE_BLOCK = 'localeBlock',
  ALERT_STRING = 'alertString',
  ALERT_BLOCK = 'alertBlock',
}

export enum DokumentNavn {
  NAVIGASJON = 'NAVIGASJON',
  FRITTSTAENDEORD_YTELSE = 'FRITTSTAENDEORD_YTELSE',
  FRITTSTAENDEORD_GEOGRAFISK_OMRADE = 'FRITTSTAENDEORD_GEOGRAFISK_OMRADE',
  FORSIDE_VEILEDERHILSEN = 'FORSIDE_VEILEDERHILSEN',
  FORSIDE_TITTEL = 'FORSIDE_TITTEL',
  FORSIDE_SPRAKVELGER = 'FORSIDE_SPRAKVELGER',
  FORSIDE_BEKREFTELSESBOKS = 'FORSIDE_BEKREFTELSESBOKS',
  FORSIDE_PUNKTLISTE = 'FORSIDE_PUNKTLISTE',
  FORSIDE_PERSONOPPLYSNINGSLENKE = 'FORSIDE_PERSONOPPLYSNINGSLENKE',
  OM_DEG_TITTEL = 'OM_DEG_TITTEL',
  OM_DEG_PERSONOPPLYSNINGER = 'OM_DEG_PERSONOPPLYSNINGER',
  OM_DEG_SPORSMAL = 'OM_DEG_SPORSMAL',
  DIN_LIVSSITUASJON_TITTEL = 'DIN_LIVSSITUASJON_TITTEL',
  DIN_LIVSSITUASJON_SPORSMAL = 'DIN_LIVSSITUASJON_SPORSMAL',
  VELG_BARN_TITTEL = 'VELG_BARN_TITTEL',
  VELG_BARN_LENKER = 'VELG_BARN_LENKER',
  VELG_BARN_KORT = 'VELG_BARN_KORT',
  OM_BARNA_TITTEL = 'OM_BARNA_TITTEL',
  OM_BARNA_SPORSMAL = 'OM_BARNA_SPORSMAL',
  OM_BARNET_TITTEL = 'OM_BARNET_TITTEL',
  OM_BARNET_FOSTERBARN = 'OM_BARNET_FOSTERBARN',
  OM_BARNET_INSTITUSJON = 'OM_BARNET_INSTITUSJON',
  OM_BARNET_UTENLANDSOPPHOLD = 'OM_BARNET_UTENLANDSOPPHOLD',
  OM_BARNET_ADOPSJON = 'OM_BARNET_ADOPSJON',
  OM_BARNET_YTELSE_FRA_EOS = 'OM_BARNET_YTELSE_FRA_EOS',
  OM_BARNET_BARNEHAGEPLASS = 'OM_BARNET_BARNEHAGEPLASS',
  OM_BARNET_ANDRE_FORELDER = 'OM_BARNET_ANDRE_FORELDER',
  OM_BARNET_BOSTED = 'OM_BARNET_BOSTED',
  MODAL_UTENLANDSOPPHOLD_SOKER = 'MODAL_UTENLANDSOPPHOLD_SOKER',
  MODAL_UTENLANDSOPPHOLD_BARN = 'MODAL_UTENLANDSOPPHOLD_BARN',
  MODAL_BARNEHAGEPLASS = 'MODAL_BARNEHAGEPLASS',
  MODAL_PENSJON_SOKER = 'MODAL_PENSJON_SOKER',
  MODAL_PENSJON_ANDRE_FORELDER = 'MODAL_PENSJON_ANDRE_FORELDER',
  MODAL_PENSJON_OMSORGSPERSON = 'MODAL_PENSJON_OMSORGSPERSON',
  MODAL_LEGG_TIL_BARN = 'MODAL_LEGG_TIL_BARN',
  MODAL_ARBEIDSPERIODE_SOKER = 'MODAL_ARBEIDSPERIODE_SOKER',
  MODAL_ARBEIDSPERIODE_ANDRE_FORELDER = 'MODAL_ARBEIDSPERIODE_ANDRE_FORELDER',
  MODAL_ARBEIDSPERIODE_OMSORGSPERSON = 'MODAL_ARBEIDSPERIODE_OMSORGSPERSON',
  MODAL_EOS_YTELSE = 'MODAL_EOS_YTELSE',
  MODAL_ANDRE_UTBETALINGER_SOKER = 'MODAL_ANDRE_UTBETALINGER_SOKER',
  MODAL_ANDRE_UTBETALINGER_ANDRE_FORELDER = 'MODAL_ANDRE_UTBETALINGER_ANDRE_FORELDER',
  MODAL_ANDRE_UTBETALINGER_OMSORGSPERSON = 'MODAL_ANDRE_UTBETALINGER_OMSORGSPERSON',
}

export const dokumentTittel: Record<DokumentNavn, string> = {
  NAVIGASJON: 'Navigasjon',
  MODAL_UTENLANDSOPPHOLD_SOKER: 'Utenlandsopphold søker',
  MODAL_UTENLANDSOPPHOLD_BARN: 'Utenlandsopphold barn',
  MODAL_BARNEHAGEPLASS: 'Barnehageplass',
  MODAL_PENSJON_SOKER: 'Pensjon søker',
  MODAL_PENSJON_ANDRE_FORELDER: 'Pensjon andre forelder',
  MODAL_PENSJON_OMSORGSPERSON: 'Pensjon omsorgsperson',
  MODAL_ARBEIDSPERIODE_SOKER: 'Arbeidsperiode søker',
  MODAL_ARBEIDSPERIODE_ANDRE_FORELDER: 'Arbeidsperiode andre forelder',
  MODAL_ARBEIDSPERIODE_OMSORGSPERSON: 'Arbeidsperiode omsorgsperson',
  MODAL_LEGG_TIL_BARN: 'Legg til barn',
  MODAL_EOS_YTELSE: 'EØS ytelse',
  MODAL_ANDRE_UTBETALINGER_SOKER: 'Andre utbetalinger søker',
  MODAL_ANDRE_UTBETALINGER_ANDRE_FORELDER: 'Andre utbetalinger andre forelder',
  MODAL_ANDRE_UTBETALINGER_OMSORGSPERSON: 'Andre utbetalinger omsorgsperson',
  FRITTSTAENDEORD_YTELSE: 'Ytelse',
  FRITTSTAENDEORD_GEOGRAFISK_OMRADE: 'Geografisk område',
  FORSIDE_VEILEDERHILSEN: 'Veilederhilsen',
  FORSIDE_TITTEL: 'Søknadstittel',
  FORSIDE_SPRAKVELGER: 'Språkvelger',
  FORSIDE_BEKREFTELSESBOKS: 'Bekreftelsesboks',
  FORSIDE_PUNKTLISTE: 'Punktliste',
  FORSIDE_PERSONOPPLYSNINGSLENKE: 'Personopplysningslenke',
  OM_DEG_TITTEL: 'Stegtittel',
  OM_DEG_PERSONOPPLYSNINGER: 'Personopplysninger',
  OM_DEG_SPORSMAL: 'Spørsmål',
  DIN_LIVSSITUASJON_TITTEL: 'Stegtittel',
  DIN_LIVSSITUASJON_SPORSMAL: 'Spørsmål',
  VELG_BARN_TITTEL: 'Stegtittel',
  VELG_BARN_LENKER: 'Lenker',
  VELG_BARN_KORT: 'Barnekort',
  OM_BARNA_SPORSMAL: 'Spørsmål',
  OM_BARNA_TITTEL: 'Stegtittel',
  OM_BARNET_TITTEL: 'Stegtittel',
  OM_BARNET_FOSTERBARN: 'Fosterbarn',
  OM_BARNET_INSTITUSJON: 'Institusjon',
  OM_BARNET_UTENLANDSOPPHOLD: 'Utenlandsopphold',
  OM_BARNET_ADOPSJON: 'Adopsjon',
  OM_BARNET_YTELSE_FRA_EOS: 'Ytelse fra eøs',
  OM_BARNET_BARNEHAGEPLASS: 'Barnehageplass',
  OM_BARNET_ANDRE_FORELDER: 'Andre forelder',
  OM_BARNET_BOSTED: 'Bosted',
};

export enum Steg {
  FORSIDE = 'FORSIDE',
  OM_DEG = 'OM_DEG',
  DIN_LIVSSITUASJON = 'DIN_LIVSSITUASJON',
  VELG_BARN = 'VELG_BARN',
  OM_BARNA = 'OM_BARNA',
  OM_BARNET = 'OM_BARNET',
  EØS_FOR_SØKER = 'EØS_FOR_SØKER',
  EØS_FOR_BARN = 'EØS_FOR_BARN',
  OPPSUMMERING = 'OPPSUMMERING',
  DOKUMENTASJON = 'DOKUMENTASJON',
  KVITTERING = 'KVITTERING',
}

export const stegTittel: Record<Steg, string> = {
  FORSIDE: 'Forside',
  OM_DEG: 'Om deg',
  DIN_LIVSSITUASJON: 'Din livssituasjon',
  VELG_BARN: 'Velg barn',
  OM_BARNA: 'Om barna',
  OM_BARNET: 'Om barnet',
  EØS_FOR_SØKER: 'Eøs for søker',
  EØS_FOR_BARN: 'Eøs for barn',
  OPPSUMMERING: 'Oppsummering',
  DOKUMENTASJON: 'Dokumentasjon',
  KVITTERING: 'Kvittering',
};

export enum Ytelse {
  ORDINÆR_BARNETRYGD = 'ORDINÆR_BARNETRYGD',
  UTVIDET_BARNETRYGD = 'UTVIDET_BARNETRYGD',
  KONTANTSTØTTE = 'KONTANTSTØTTE',
}

export enum EFlettefelt {
  BARN_NAVN = 'BARN_NAVN',
  SØKER_NAVN = 'SØKER_NAVN',
  YTELSE = 'YTELSE',
  UTLANDET_NORGE = 'UTLANDET_NORGE',
  PERSONTYPE = 'PERSONTYPE',
  I_UTENFOR = 'I_UTENFOR',
}
