name: Build and deploy prod
on:
  push:
    branches:
      - 'master'

jobs:
  sanity-deploy:
    runs-on: ubuntu-20.04
    name: Deploy Sanity
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          yarn

      - name: Deploy
        run: |
          SANITY_AUTH_TOKEN="${{ secrets.SANITY_DEPLOY_TOKEN }}" \
          npx sanity deploy