name: Build and deploy prod
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  sanity-deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          cache-dependency-path: ./package.json
          node-version: 20

      - name: Yarn
        run: yarn install

      - name: Deploy sanity
        uses: sanity-io/github-action-sanity@v0.7-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}
        with:
          args: deploy