name: Build and deploy prod
on:
  push:
    branches:
      - '*'

jobs:
  sanity-deploy:
    runs-on: ubuntu-18.04
    name: Deploy Sanity
    steps:
      - uses: actions/checkout@v2
      - uses: sanity-io/github-action-sanity@v0.2-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}
          NPM_TOKEN: ${{ secrets.READER_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        with:
          args: deploy