name: Build and deploy prod
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  sanity-deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # ratchet:actions/setup-node@v3
        with:
          cache: yarn
          cache-dependency-path: ./package.json
          node-version: 24

      - name: Installer sanity
        run: yarn global add @sanity/cli && sanity install

      - name: Deploy sanity
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}
        run: sanity deploy
