name: Oppdater testsett KS
on:
  workflow_dispatch:

jobs:
  oppdater-testsett:
    runs-on: ubuntu-latest
    name: Oppdater testsett KS manuelt
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4

      - name: Install dependencies
        run: |
          yarn --prefer-offline --frozen-lockfile --ignore-scripts

      - name: Export prod dataset
        run: |
          SANITY_AUTH_TOKEN="${{ secrets.SANITY_VIEWER_TOKEN }}" \
          npx sanity dataset export \
          ks-production backups/baks-soknad-ks-prod.tar.gz

      - name: Import prod dataset til test
        run: |-
          SANITY_AUTH_TOKEN="${{ secrets.SANITY_WRITE_TOKEN }}" \
          npx sanity dataset import \
          backups/baks-soknad-ks-prod.tar.gz ks-test --replace

